---
- hosts: all
  tasks:
  - name: find who is executing
    command: whoami
  - name: ping all machines
    ping: 
  - name: find current directory
    command: pwd
  - name: uninstall tree
    yum:
      name: tree
      state: absent
      