---
- hosts: appserver
  become: yes
  tasks:
  - name: install openjdk 8
    yum: 
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: install tomcat
    yum:
      name: tomcat
      state: present
  - name: download jenkins to webapps/
    get_url:
      url: https://mirrors.tuna.tsinghua.edu.cn/jenkins/war-stable/2.277.4/jenkins.war
      dest: /usr/share/tomcat/webapps/jenkins.war
  - name: enable and start tomcat
    service: 
      name: tomcat
      state: started
      enabled: yes
